// <auto-generated />
using BackendRandomizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendRandomizer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916114948_AddMoreAttachments")]
    partial class AddMoreAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("BackendRandomizer.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "7.62x39 Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "AKM Premium Stable Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "AKM Precision Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "AK Series 7.62x39 Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "AKM Standard Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "AKM Stabilized Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "AKM Compatible Hexagon Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "AK Guard Muzzle Brake",
                            Slot = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Classic Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Multi-Port Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Precission Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "AR-10 Muzzle Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "MG 3 Muzzle Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mk14/M14 Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "7.62x51mm Caliber SureFire Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "191 Muzzle Compensator",
                            Slot = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "T19X Flash Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "U191 Suppressor",
                            Slot = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "1x/4x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "1x/6x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 21,
                            Name = "2x Sight*",
                            Slot = 0
                        },
                        new
                        {
                            Id = 22,
                            Name = "3.5x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 23,
                            Name = "6.5/20x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 24,
                            Name = "2x/7x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 25,
                            Name = "4x/16x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 26,
                            Name = "3x Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 27,
                            Name = "3x Combination Holographic Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 28,
                            Name = "4x Holographic Triangle Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 29,
                            Name = "533 Holographic Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 30,
                            Name = "EKP-8-18 Reflex Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Bat Ear Holographic Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Classic Holographic Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 33,
                            Name = "Classic Compact Red Dot Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 34,
                            Name = "Whirlpool Holographic Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 35,
                            Name = "Periscope Hybrid Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 36,
                            Name = "M1 Tactical Red Dot",
                            Slot = 0
                        },
                        new
                        {
                            Id = 37,
                            Name = "Modern Red Dot Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 38,
                            Name = "PK-06 Reflex Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 39,
                            Name = "PZ4 THERMAL SCOPE",
                            Slot = 0
                        },
                        new
                        {
                            Id = 40,
                            Name = "Raised Precision Red Dot Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 41,
                            Name = "Simple Red Dot Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 42,
                            Name = "Tactical Red Dot Scope",
                            Slot = 0
                        },
                        new
                        {
                            Id = 43,
                            Name = "Triangle Precision Sight",
                            Slot = 0
                        },
                        new
                        {
                            Id = 44,
                            Name = "AK Compatible Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 45,
                            Name = "Industrial AK Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 46,
                            Name = "AK Modern Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 47,
                            Name = "AK 12 Standard Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 48,
                            Name = "KGB Lightweight AK Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 49,
                            Name = "Lightweight AK Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 50,
                            Name = "RK-3 Industrial AK Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 51,
                            Name = "SAW Tactical AK Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 52,
                            Name = "AK Series Standard Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 53,
                            Name = "Dedicated FAL Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 54,
                            Name = "FAL Comfortable Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 55,
                            Name = "T19X Standard Rear Grip",
                            Slot = 4
                        },
                        new
                        {
                            Id = 56,
                            Name = "Type 81 Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 57,
                            Name = "AK-74 Wooden Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 58,
                            Name = "AK Series High-Performance Buttstock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 59,
                            Name = "AK-74 Polymer Bootstock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 60,
                            Name = "AK Series AP Tactical Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 61,
                            Name = "AK Series FAB Buttstock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 62,
                            Name = "AK Series GS FixedStock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 63,
                            Name = "AK Series GS Modern Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 64,
                            Name = "AK Series ME Modern Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 65,
                            Name = "AK-Series SF Gen 2 Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 66,
                            Name = "AK-Series SF Lightweight Buttstock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 67,
                            Name = "FAL Lightweight Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 68,
                            Name = "FAL Polymer Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 69,
                            Name = "FAL Special Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 70,
                            Name = "FAL Stable Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 71,
                            Name = "FAL Triangle Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 72,
                            Name = "191 Assault Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 73,
                            Name = "191 Sniper Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 74,
                            Name = "T19X Standard Stock",
                            Slot = 1
                        },
                        new
                        {
                            Id = 75,
                            Name = "Alloy Tactical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 76,
                            Name = "Alluminum Vertical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 77,
                            Name = "Comfortable Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 78,
                            Name = "KIR Tilt Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 79,
                            Name = "Lightweight Tactical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 80,
                            Name = "Lightweight Long Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 81,
                            Name = "Lightweight Short Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 82,
                            Name = "Lightweight Tilt Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 83,
                            Name = "Lightweight Tactical Vertical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 84,
                            Name = "RK-O Control Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 85,
                            Name = "RK-6 Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 86,
                            Name = "Short Vertical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 87,
                            Name = "B25 Tilt Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 88,
                            Name = "Stable Triangular Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 89,
                            Name = "Vertical Front Grip",
                            Slot = 3
                        },
                        new
                        {
                            Id = 90,
                            Name = "NO GRIP",
                            Slot = 3
                        });
                });

            modelBuilder.Entity("BackendRandomizer.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeaponCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AKM",
                            WeaponCategory = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "FAL",
                            WeaponCategory = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "T191",
                            WeaponCategory = 0
                        });
                });

            modelBuilder.Entity("BackendRandomizer.Models.WeaponAttachment", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeaponId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("WeaponAttachments");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 1
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 2
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 3
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 4
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 5
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 8
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 19
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 20
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 21
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 22
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 23
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 24
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 25
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 26
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 27
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 28
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 29
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 30
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 31
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 32
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 33
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 34
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 35
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 36
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 37
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 38
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 39
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 40
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 41
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 42
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 43
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 44
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 45
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 46
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 47
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 48
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 49
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 50
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 51
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 52
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 56
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 57
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 58
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 59
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 60
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 61
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 62
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 63
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 64
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 65
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 66
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 75
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 76
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 77
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 78
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 79
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 80
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 81
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 82
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 83
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 84
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 85
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 86
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 87
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 88
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 89
                        },
                        new
                        {
                            WeaponId = 1,
                            AttachmentId = 90
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 9
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 10
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 11
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 12
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 13
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 14
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 15
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 19
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 20
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 21
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 22
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 23
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 24
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 25
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 26
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 27
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 28
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 29
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 30
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 31
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 32
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 33
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 34
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 35
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 36
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 37
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 38
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 39
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 40
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 41
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 42
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 43
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 53
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 54
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 67
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 68
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 69
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 70
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 71
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 75
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 76
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 77
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 78
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 79
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 80
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 81
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 82
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 83
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 84
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 85
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 86
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 87
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 88
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 89
                        },
                        new
                        {
                            WeaponId = 2,
                            AttachmentId = 90
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 16
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 17
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 18
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 19
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 20
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 21
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 22
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 23
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 24
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 25
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 26
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 27
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 28
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 29
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 30
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 31
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 32
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 33
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 34
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 35
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 36
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 37
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 38
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 39
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 40
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 41
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 42
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 43
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 55
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 72
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 73
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 74
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 75
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 76
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 77
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 78
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 79
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 80
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 81
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 82
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 83
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 84
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 85
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 86
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 87
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 88
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 89
                        },
                        new
                        {
                            WeaponId = 3,
                            AttachmentId = 90
                        });
                });

            modelBuilder.Entity("BackendRandomizer.Models.WeaponAttachment", b =>
                {
                    b.HasOne("BackendRandomizer.Models.Attachment", "Attachment")
                        .WithMany("WeaponAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendRandomizer.Models.Weapon", "Weapon")
                        .WithMany("WeaponAttachments")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("BackendRandomizer.Models.Attachment", b =>
                {
                    b.Navigation("WeaponAttachments");
                });

            modelBuilder.Entity("BackendRandomizer.Models.Weapon", b =>
                {
                    b.Navigation("WeaponAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
